spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/kenakata
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
